[project]
name = "py-mcp-naver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=0.4.1",
    "httpx>=0.28.1",
    "pydantic>=2.10.6",
    "xmltodict>=0.14.2",
]
